我们写代码时，容易遇到错误和程序异常，`Python`会很贴心地提示我们。比如说这样！
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/20210124084506386.png)
还有这样：
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/20210124084616522.png)
以及这样：
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/20210124085055422.png)
……还有很多，它们都称之为异常。
<hr>

## 异常都有哪些？
请看下表（以下是内置异常）：

```python
异常名称	描述
BaseException	所有异常的基类
SystemExit	解释器请求退出
KeyboardInterrupt	用户中断执行(通常是输入^C)
Exception	常规错误的基类
StopIteration	迭代器没有更多的值
GeneratorExit	生成器(generator)发生异常来通知退出
SystemExit	Python 解释器请求退出
StandardError	所有的内建标准异常的基类
ArithmeticError	所有数值计算错误的基类
FloatingPointError	浮点计算错误
OverflowError	数值运算超出最大限制
ZeroDivisionError	除(或取模)零 (所有数据类型)
AssertionError	断言语句失败
AttributeError	对象没有这个属性
EOFError	没有内建输入,到达EOF 标记
EnvironmentError	操作系统错误的基类
IOError	输入/输出操作失败
OSError	操作系统错误
WindowsError	系统调用失败
ImportError	导入模块/对象失败
KeyboardInterrupt	用户中断执行(通常是输入^C)
LookupError	无效数据查询的基类
IndexError	序列中没有没有此索引(index)
KeyError	映射中没有这个键
MemoryError	内存溢出错误(对于Python 解释器不是致命的)
NameError	未声明/初始化对象 (没有属性)
UnboundLocalError	访问未初始化的本地变量
ReferenceError	弱引用(Weak reference)试图访问已经垃圾回收了的对象
RuntimeError	一般的运行时错误
NotImplementedError	尚未实现的方法
SyntaxError	Python 语法错误
IndentationError	缩进错误
TabError	Tab 和空格混用
SystemError	一般的解释器系统错误
TypeError	对类型无效的操作
ValueError	传入无效的参数
UnicodeError	Unicode 相关的错误
UnicodeDecodeError	Unicode 解码时的错误
UnicodeEncodeError	Unicode 编码时错误
UnicodeTranslateError	Unicode 转换时错误
Warning	警告的基类
DeprecationWarning	关于被弃用的特征的警告
FutureWarning	关于构造将来语义会有改变的警告
OverflowWarning	旧的关于自动提升为长整型(long)的警告
PendingDeprecationWarning	关于特性将会被废弃的警告
RuntimeWarning	可疑的运行时行为(runtime behavior)的警告
SyntaxWarning	可疑的语法的警告
UserWarning	用户代码生成的警告


——————————————————————————————————————————————————
不包括自定义的异常。
来自：https://www.cnblogs.com/liujiacai/p/10280323.html
```

<hr>

## 如何抛出异常？
异常可以让我们抛出，适合在模块中使用。
我们来认识一下抛出错误的语句——`raise`语句。
格式：`raise 错误名称(提示内容)`，操作一下：

```python
raise SyntaxError('语法错误！')
```
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/20210124091102898.png)
只要是内置异常或自定义设好了的，都可以使用。

<hr>

## 怎么自定义一个新的异常？
我们可以自定义异常，代码格式：

```python
class 异常名称(Exception):
	def __init__(self):
		pass
	def __str__(self):
		return 错误信息
```
甚至可以支持汉语：

```python
class 错误类是可以支持汉语的(Exception):
    def __init__(self):
        pass
    def __str__(self):
        return '错误信息'
    
raise 错误类是可以支持汉语的
```
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/2021012409180791.png)
尽管编辑器可能会提示错误，但是可以运行。
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/20210124091916123.png?x-oss-process=image/watermark,type_ZmFuZ3poZW5naGVpdGk,shadow_10,text_aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L1BhbkRhb3hpMjAyMA==,size_16,color_FFFFFF,t_70)

<hr>

## 如何检测异常？
我们可以通过`try except`语句检测异常，格式如下：

```python
try:
	要检测的代码
except 异常名称:
	处理这个异常的代码
```
可以有无限个`except`，有点类似于`if语句`，如果要是遇到错误就输出，那么代码写成这样：

```python
try:
	要检测的代码
except Exception as e:
	print('错误！',e)
```
来做个小测试：

```python
while True:
	try:
		number = int(input('请输入一个数字：'))
	except ValueError:
		print('您输入的内容无效！')
```
这样就用户输入不是数字的内容时，就会触发错误检测，提示用户输入内容无效。
![在这里插入图片描述](https://pic.2ge.org/cdn/?url=https://img-blog.csdnimg.cn/2021012409340276.png)

<hr>

```python
练习题
请自定义一个名为ZiDingYiError的异常，抛出它时输出'自定义异常'，并将它抛出。
```

